
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from hooks.py and the example nodes in
# `src/pipelines/`
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#parameters

SIZE_ANALYSIS: 8000 # not analyze on a whole dataset

BATCH_ANALYSIS: 160
BATCH_SIZE: 40 #40
BATCH_DESCENT_SIZE: 20
BATCH_DESCENT_RATE: 0
BATCH_ASCENT_SIZE: 20
BATCH_ASCENT_RATE: 0

LAMBDA: normal # normal, small, big
N_INIT: 100 # should be >= 0 / choose 100
BUDGET: 600
N_SIMULATIONS: 10 # 3 or 5 for debug
BATCH_SEQ: [10, 20, 40, 80, 100, 120, 140, 160, 180, 200]
#[40, 80, 100, 200]

BUDGET_SEQ: [200, 250, 300, 350, 400, 450, 500]
