
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from hooks.py and the example nodes in
# `src/pipelines/`
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#parameters

N_INIT: 100
SIZE_ANALYSIS: 8000
BATCH_SIZE: 40 #40

BUDGET: 600
N_SIMULATIONS: 10
BATCH_SEQ: [10, 20, 40, 80, 100, 120, 140, 160, 180, 200]
#[40, 80, 100, 200]

BUDGET_SEQ: [300, 400, 500, 600]